version: "3"
services:
  authsvr:
    image: ws-project/authsvr:1
    ports:
      - 8901:8901
    environment:
      PROFILE: "dev"
      EUREKASERVER_URI: "http://eurekasvr:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      CONFIGSERVER_URI: "http://confsvr:8888"
      CONFIGSERVER_PORT: "8888"
      DATABASESERVER_PORT: "3306"  
      ENCRYPT_KEY: ${ENCRYPT_KEY}
  confsvr:
    image: ws-project/confsvr:1
    ports:
      - 8888:8888
    environment:
      ENCRYPT_KEY: ${ENCRYPT_KEY}
  eurekasvr:
    image: ws-project/eurekasvr:1
    ports:
      - 8761:8761
  zuulsvr:
    image: ws-project/zuulsvr:1
    ports:
      - 5555:5555
    environment:
      PROFILE: "dev"
      EUREKASERVER_URI: "http://eurekasvr:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      CONFIGSERVER_URI: "http://confsvr:8888"
      CONFIGSERVER_PORT: "8888"