version: "2"
services:
  ws-service:
    image: ws-project/ws-service:1
    ports:
      - 8080:8080
    environment:
      PROFILE: "dev"
      CONFIGSERVER_URI: "http://confsvr:8888"
      CONFIGSERVER_PORT: "8888"
      DATABASESERVER_PORT: "3306"
      EUREKASERVER_URI: "http://eurekasvr:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      ENCRYPT_KEY: ${ENCRYPT_KEY}
  confsvr:
    image: ws-project/confsvr:1
    ports:
      - 8888:8888
    environment:
      EUREKASERVER_URI: "http://eurekasvr:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      ENCRYPT_KEY: ${ENCRYPT_KEY}
  eurekasvr:
    image: ws-project/eurekasvr:1
    ports:
      - 8761:8761
  database:
    image: mariadb:10.1
    ports:
       - 3307:3306
    restart: always
    environment:
       MYSQL_DATABASE: ws_service
       MYSQL_ROOT_PASSWORD: mslim8803
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci